export const Db_ACTIONS = {
  UPDATE_CASH_REGISTER: "UPDATE_CASH_REGISTER",

  //Products Actions
  UPDATE_STOCK: "UPDATE_STOCK",

  UPDATE_USERS: "UPDATE_USERS",

  //Form ACtions
  UPDATE_DATAFORM: "UPDATE_DATAFORM",
  EDIT_DATAFORM: "EDIT_DATAFORM",
  CLEAR_DATAFORM: "CLEAR_DATAFORM",
};
